### ISSUE TITLE
Visualizer does not work when audio device is configured as 5.1/7.1

### ISSUE THREAD

**Issue by guiliphy** [AterialDawn/CUEAudioVisualizer#3]
Hi there,

when I run the visualizer either via my speakers (5.1) or my gaming headset (7.1), I get the error BASS_ERROR_FORMAT. If I set either device to stereo via the windows sound menu, the visualizer works as normal.

Really like your visualizer, but I honestly can't be bothered switching my system to stereo every time I want to see it.

Thanks for making this awesome visualizer :)

**Comment by pcnorden** [comment]
Hey, just dropping you a line to recommend that you maybe could use [DarthAffe's visualizer](https://github.com/DarthAffe/KeyboardAudioVisualizer) instead. It supports 5.1 and 7.1 sound systems and is generally a bit easier to work with.

Take care!
