### ISSUE TITLE
Program closes immediately.

### ISSUE THREAD

**Issue by Azortharion** [AterialDawn/CUEAudioVisualizer#4]
Keyboard: K95 RGB Platinum
Windows 10 Pro 64-bit

The program appears in the notification bar after opening and the keyboard's existing default profile (rainbow-y) turns off. After roughly 2 seconds, the program closes in the notification bar and the keyboard flicks back to default.

**Comment by pcnorden** [comment]
What sound system do you use when this occurs?

**Comment by aFlyerz** [comment]
Keyboard: K95 RGB Platinum
Windows 10 Pro 64-bit

Same problem for me using 2 sound system : Realtek Digital Output(Optical) so an optical output and an usb output. But desactivate them once by once still doesn't work. In admin mode the program crash faster. Compatibility version don't work. Hope you can fix that if you have any question.

**Comment by Owd-Larrd** [comment]
Working fllawlessly for circa 18month on my Strafe Cherry MX Red (not RGB), now showing same as above, Win 10 64-bit is my OS, running latest FW and CUE

**Comment by pcnorden** [comment]
Alrighty... Anybody in here a programmer? If so, please give me _something_ to work with.

Steps if you are not a programmer:

1. Install Visual Studio 2015
2. Clone this project and load up the solution in Visual Studio (double-click the .sln file in the extracted folder)
3. Press F5 and let me know **WHERE** the point (Line # and what file) is where it fails! (Bonus points for screenshots of the Visual Studio window)

I'm sorry if I sound like I'm being rude, but apparantly I might get fired from my job, so I'm not really happy at the moment

**Comment by musakasim** [comment]
![screenshot 2017-11-12 06 16 24](https://user-images.githubusercontent.com/1035273/32695598-2ca6e8b8-c771-11e7-885a-cc80bba831fb.png)
Well something goes wrong in CueSDK.Initialize,
updating to new CueSdk just works fine,
I think [DarthAffe's fork](https://github.com/DarthAffe/CUEAudioVisualizer)  should be merged to master which just works fine for me.
Thanks for the app again .

**Comment by pcnorden** [comment]
Huh, that is something that I never expected to be a problem.

Also, I'm not the owner of this repository, so I unfortunately can't merge or upload anything to the repository and @AterialDawn has gone radio-silent.

Thanks anyway for finding what went wrong. Maybe people can find this post and download the fork and compile it themselfes =)

**Comment by musakasim** [comment]
Well I belive compiling is something pain in the a.. , so while I got my hands on it I put the compiled files here.
Anyone may download it with this link:
[CUEAudioVisualizer(DarthAffe fork).zip](https://github.com/AterialDawn/CUEAudioVisualizer/files/1465613/CUEAudioVisualizer.DarthAffe.fork.zip)

**Comment by aFlyerz** [comment]
Thanks musakasim, don't have time to recompile myself, works fine now.

**Comment by Owd-Larrd** [comment]
@pcnorden and @musakasim thank you both, you're right to say i'm an infrastructure guy, last programming I did was Fortran 5 !!!  Thank you again, most appreciated.

**Comment by pcnorden** [comment]
Just dropping a line here to tell you all about (DartAffe's visualizer)[https://github.com/DarthAffe/KeyboardAudioVisualizer].

It works a LOT better with 5.1 and 7.1 audio systems.

Take care!
