### ISSUE TITLE
Program don't start

### ISSUE THREAD

**Issue by aFlyerz** [AterialDawn/CUEAudioVisualizer#5]
Hi, I writing this new issue because the other one seems to be ignored. So the program don't start or start just for 2/3 seconds. I just re-install windows 10 completely. My keyboard is K95 Platinium. If you need any other info.
Greetings

**Comment by pcnorden** [comment]
Do you have any knowledge of using C# inside Visual Studio?
If so, please load up the project and run it. Where does the program error out?
If not, please tell me, and I'll try to make a video on how to set up up and run it.

**Comment by pcnorden** [comment]
@aFlyerz You maybe want to check out (DartAffe's visualizer)[https://github.com/DarthAffe/KeyboardAudioVisualizer]

Quite neat stuff AND it supports 5.1 and 7.1 audio.

Take care!

**Comment by Popets** [comment]
Hi
I have the same problem with it not being able to start and I have found the problem.
In the SpectrumPlugin.cs on line 46, 79, 109, 139 you have used the barsample index. But that is calculated by the bar count which starts from 1, while the index should start from 0 so you should do a -1 on all of the indexes on the lines shown.

**Comment by Popets** [comment]
I have fixed this but I am not allowed to commit into this repo even on another branch. If you allowed me to create a branch and commit to it that would be great.

**Comment by pcnorden** [comment]
I can't do a single thing since it's @AterialDawn that owns this repo so I can't do anything, sorry.

You can however fork of your own and then upload the modified files there?

Take care!

**Comment by AterialDawn** [comment]
Sorry, I don't have much spare time, and seeing as I don't use this anymore myself, I don't really have too much interest in fixing this. Apologies to anyone still interested in this.
Consider giving [DarthAffe's Version](https://github.com/DarthAffe/KeyboardAudioVisualizer) a look instead!
