### ISSUE TITLE
Program Doesn't Work At All w/ K55 and Harpoon RGB

### ISSUE THREAD

**Issue by Incrested** [AterialDawn/CUEAudioVisualizer#7]
I tried both the compiled versions of AterialDawn and the recommended DarthAffe fork. Both are, in the iCUE app, labeled as controlling the lighting via a third-party app (of course, these apps). I don't run either at the same time, nor any other programs running the SDK. I have a slight belief that the K55 and/or Harpoon RGB mouse could not be supported, but I wanted to be sure beforehand. I'm willing to pop open my copy of VS17 and provide any useful logs and debugging info if needed.

**Comment by pcnorden** [comment]
I'm not the maintainer/owner of this repo, but since it looks like AterialDawn has totally abandoned this repo, I highly suggest to use DarthAffe's [KeyboardAudioVisualizer](https://github.com/DarthAffe/KeyboardAudioVisualizer) repo as it has updated SDK and generally works better.

Take care!

**Comment by Incrested** [comment]
Alrighty, thanks! I actually remembered that the K55 has 3 zones and I suppose that it technically wouldn't work then. I'll try it anyways, thanks!
